import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { ArrowRight } from "lucide-react";

const dimensions = [
  {
    num: 1,
    name: "CFR Compliance",
    checks: "Correct 38 CFR sections cited for your condition",
  },
  {
    num: 2,
    name: "Nexus Strength",
    checks: "Clear medical link using required nexus language",
  },
  {
    num: 3,
    name: "Evidence Grounding",
    checks: "Tied to your actual records, not generic language",
  },
  {
    num: 4,
    name: "Diagnostic Clarity",
    checks: "Condition named, rated, and functionally described",
  },
  {
    num: 5,
    name: "Rater Readiness",
    checks: "Formatted so a rater can act on it immediately",
  },
];

interface RpaScoringModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  authenticated?: boolean;
}

export function RpaScoringModal({
  open,
  onOpenChange,
  authenticated = false,
}: RpaScoringModalProps) {
  const ctaHref = authenticated ? "/generate" : "/api/login";

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent
        className="max-w-xl p-0 overflow-hidden border-none"
        data-testid="modal-rpa-scoring"
      >
        <div
          className="p-6 sm:p-8"
          style={{
            background: "linear-gradient(135deg, #0D2137 0%, #163352 55%, #1a3d60 100%)",
            color: "#FAFAF7",
          }}
        >
          <DialogHeader className="space-y-3 mb-5">
            <DialogTitle
              className="text-xl sm:text-2xl font-bold tracking-tight"
              style={{ color: "#FAFAF7" }}
              data-testid="text-rpa-modal-title"
            >
              Is Your Letter Actually Ready to Win?
            </DialogTitle>
            <DialogDescription
              className="text-sm sm:text-base leading-relaxed"
              style={{ color: "rgba(250,250,247,0.78)" }}
              data-testid="text-rpa-modal-description"
            >
              Every letter generated by Nexus247 is automatically scored across 5
              dimensions before you ever hit submit — the same criteria a VA rater
              uses to evaluate your claim.
            </DialogDescription>
          </DialogHeader>

          <div className="rounded-md overflow-hidden mb-5" style={{ border: "1px solid rgba(200,153,58,0.25)" }}>
            <table className="w-full text-sm" data-testid="table-rpa-dimensions">
              <thead>
                <tr style={{ background: "rgba(200,153,58,0.12)" }}>
                  <th className="px-3 py-2 text-left font-semibold" style={{ color: "#D4A43E", width: "2rem" }}>#</th>
                  <th className="px-3 py-2 text-left font-semibold" style={{ color: "#D4A43E" }}>Dimension</th>
                  <th className="px-3 py-2 text-left font-semibold" style={{ color: "#D4A43E" }}>What It Checks</th>
                </tr>
              </thead>
              <tbody>
                {dimensions.map((d, i) => (
                  <tr
                    key={d.num}
                    style={{
                      background: i % 2 === 0 ? "rgba(255,255,255,0.03)" : "transparent",
                      borderTop: "1px solid rgba(200,153,58,0.12)",
                    }}
                    data-testid={`row-dimension-${d.num}`}
                  >
                    <td className="px-3 py-2.5 font-medium" style={{ color: "#D4A43E" }}>{d.num}</td>
                    <td className="px-3 py-2.5 font-medium whitespace-nowrap" style={{ color: "#FAFAF7" }}>{d.name}</td>
                    <td className="px-3 py-2.5" style={{ color: "rgba(250,250,247,0.72)" }}>{d.checks}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          <p
            className="text-xs sm:text-sm mb-6 leading-relaxed"
            style={{ color: "rgba(250,250,247,0.65)" }}
            data-testid="text-rpa-modal-footer"
          >
            A letter that scores below threshold gets flagged for revision — before
            it costs you.
          </p>

          <a href={ctaHref} data-testid="link-rpa-see-score">
            <Button
              className="w-full font-semibold"
              style={{
                background: "#D4A43E",
                color: "#0D2137",
                borderColor: "#D4A43E",
              }}
              data-testid="button-rpa-see-score"
            >
              See My Score
              <ArrowRight className="ml-2 h-4 w-4" />
            </Button>
          </a>
        </div>
      </DialogContent>
    </Dialog>
  );
}
